server:
  port: 6500

spring:
  application:
    name: auth_service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables service discovery with Eureka
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
